# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqwH5Lk5QCUADxfgBdMV_1DxNvTPh2Ls
"""
1.
# Scenario: Customer Support Chatbot Training
# Imagine you’re building a customer support chatbot for an e-commerce company.
# The chatbot needs to understand different types of sentences so it can respond appropriately.
# You feed it these sentences:
# - “Machine learning is a subset of AI”
# - “Deep learning uses neural networks”
# - “Bananas are yellow fruits”
# - “Artificial intelligence powers chatbots”




from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    "Machine learning is a subset of AI",
    "Deep learning uses neural networks",
    "Bananas are yellow fruits",
    "Artificial intelligence powers chatbots"
]

embeddings = model.encode(sentences)

print(embeddings.shape)

# Scenario: Fitness & Wellness Chatbot Training
# You feed it these sentences:
# - “Push-ups strengthen chest and triceps”
# - “Yoga improves flexibility and balance”
# - “Apples are rich in fiber”
# - “Cardio exercises boost heart health”
# 👉 In this case, the chatbot learns to distinguish between exercise facts, nutrition facts, and general wellness statements, so it can tailor its responses — e.g., suggesting workouts, offering diet tips, or explaining health benefits.
# Would you like me to design a third scenario (maybe in education or travel) so you have a set of examples across different industries?

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    "Push-ups strengthen chest and triceps",
    "Yoga improves flexibility and balance",
    "Apples are rich in fiber",
    "Cardio exercises boost heart health"
]

embeddings = model.encode(sentences)

print(embeddings.shape)

# Simple cosine similarity example
import numpy as np

def cosine_similarity(a, b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

a = np.array([0.2,0.8,-0.3,0.5])
b = np.array([0.1,0.9,-0.2,0.4])

print(cosine_similarity(a,b))


2.
# Scenario: Healthcare Chatbot – Patient Symptom Matching
# Imagine you’re designing a healthcare chatbot that helps patients find possible conditions based on their symptoms. Both patients and conditions are represented as vectors of features (e.g., fever, cough, fatigue, headache).
# - Patient’s symptom vector:
# [0.2,0.8,-0.3,0.5] → mild fever, strong cough, no fatigue, moderate headache.
# - Condition’s symptom profile vector:
# [0.1,0.9,-0.2,0.4] → mild fever, strong cough, little fatigue, moderate headache.
# The chatbot uses cosine similarity to measure how closely the patient’s symptoms align with the condition’s profile

import numpy as np

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

patient_symptoms = np.array([0.2, 0.8, -0.3, 0.5])
condition_profile = np.array([0.1, 0.9, -0.2, 0.4])

similarity = cosine_similarity(patient_symptoms, condition_profile)

print(similarity)

#Simple Euclidean Distance example
import numpy as np
a=np.array([1,2])
b=np.array([4,6])
distance=np.linalg.norm(a-b)
print(distance)


3.
# Scenario: Warehouse Robot Navigation
# Imagine a warehouse where a robot needs to pick up items.
# - The robot is currently at position (1,2) on the warehouse grid.
# - The item it needs to collect is stored at position (4,6).
# The robot’s navigation system calculates the straight-line distance to the item so it knows how far it must travel if it moves directly.

import numpy as np

robot = np.array([1,2])
item = np.array([4,6])

distance = np.linalg.norm(robot - item)

print(distance)

#example of Dot Product (Fastest Similarity Method)
import numpy as np

a = np.array([1,3,5])
b = np.array([2,4,6])

print(np.dot(a,b))


4.
# Scenario: Basketball Player Evaluation
# A coach is evaluating how well a player’s skills match the team’s current needs.
# - The team’s requirement vector is a = [2,5,1].
# - 2 = need for shooting ability
# - 5 = need for defense
# - 1 = need for passing
# - The player’s skill vector is b = [3,4,2].
# - 3 = player’s shooting ability
# - 4 = defensive ability
# - 2 = passing ability
# The coach calculates the dot product:

import numpy as np

requirement_vector = np.array([2,5,1])
skill_vector= np.array([3,4,2])

print(np.dot(requirement_vector,skill_vector))


5.
# # 🛒 Scenario: E‑Commerce Product Recommendations
# # Imagine you’re building a smart recommendation engine for an online store.
# # - Problem: Customers often search with phrases like “comfortable running shoes”,
#  but the catalog has items
# #  titled “lightweight sneakers for jogging”. Traditional keyword
#  search struggles to connect these.
# # - Solution: Use embeddings to capture semantic meaning of product
# descriptions and customer queries.

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Customer query embedding
query_embedding = np.array([0.1, 0.8, 0.5])

# Product catalog embeddings
product_embeddings = {
    "lightweight sneakers for jogging": np.array([0.2, 0.7, 0.6]),
    "formal leather shoes": np.array([0.9, 0.1, 0.2]),
    "sandals for summer": np.array([0.3, 0.4, 0.5])
}

#Compute similarity between query and each product
for product, embedding in product_embeddings.items():
    similarity = np.dot(query_embedding, embedding)
    cosine_sim = cosine_similarity([query_embedding], [embedding])[0][0]
    print(f"{product} → Dot Product: {similarity:.3f}, Cosine Similarity: {cosine_sim:.3f}")

#  Recommendation: pick the product with highest similarity
best_match = max(product_embeddings.items(), key=lambda x: np.dot(query_embedding, x[1]))
print("\nRecommended Product:", best_match[0])


6.
#  Scenario: Online Learning Platform Recommendations
# Imagine you’re building a smart recommendation engine for an online education platform.
# - Problem: Students often search with phrases like “beginner-friendly Python tutorials”, but the course catalog has items titled “Introduction to Programming with Python”. Traditional keyword search struggles to connect these because the words don’t match exactly.
# - Solution: Use embeddings to capture the semantic meaning of both student queries and course descriptions. By comparing embeddings with dot product or cosine similarity, the system can recommend the most relevant courses even when the wording is different

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 🎓 Student search query embedding
query_embedding = np.array([0.2, 0.7, 0.6])

# 📚 Course catalog embeddings
course_embeddings = {
    "Introduction to Programming with Python": np.array([0.3, 0.8, 0.5]),
    "Advanced Data Science with R": np.array([0.9, 0.2, 0.1]),
    "Web Development with HTML and CSS": np.array([0.4, 0.3, 0.6])
}

# 🔍 Calculate similarity between query and each course
for course, embedding in course_embeddings.items():
    similarity = np.dot(query_embedding, embedding)
    cosine_sim = cosine_similarity([query_embedding], [embedding])[0][0]
    print(f"{course} → Dot Product: {similarity:.3f}, Cosine Similarity: {cosine_sim:.3f}")

# ✅ Recommend the best matching course
best_match = max(course_embeddings.items(), key=lambda x: np.dot(query_embedding, x[1]))

print("\nRecommended Course:", best_match[0])


7.
# Scenario: Hospital FAQ Assistant
# A hospital wants to build a chatbot that helps patients quickly find answers to common questions.
# - Problem: Patients ask questions in different ways. For example:
# - “How do I book an appointment?”
# - “What’s the process to schedule a doctor visit?”
# - “Can I see a physician tomorrow?”
# Traditional keyword search might miss these connections.
# - Solution: Convert FAQs and patient queries into embeddings, then measure similarity to find the closest match.


import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Patient query embedding
query_embedding = np.array([0.3, 0.7, 0.6])

#FAQ embeddings
faq_embeddings = {
    "How can I book an appointment with a doctor?": np.array([0.2, 0.8, 0.6]),
    "What are the hospital visiting hours?": np.array([0.7, 0.2, 0.3]),
    "How do I pay my hospital bill online?": np.array([0.6, 0.3, 0.2])
}

# Calculate similarity between query and FAQs
for question, embedding in faq_embeddings.items():
    similarity = np.dot(query_embedding, embedding)
    cosine_sim = cosine_similarity([query_embedding], [embedding])[0][0]
    print(f"{question} → Dot Product: {similarity:.3f}, Cosine Similarity: {cosine_sim:.3f}")

#  Find the best matching FAQ
best_match = max(faq_embeddings.items(), key=lambda x: np.dot(query_embedding, x[1]))

print("\nBest FAQ Answer:", best_match[0])


8.
#  Scenario: Package Delivery in a City
# Imagine you run a delivery company in a huge city with 100,000 houses. Each house has a
#  unique “address fingerprint” (like the 384‑dimensional vectors in your code).
# Now, when a customer places an order, you need to quickly find the nearest warehouse or
#  delivery hub to their house. Instead of checking every single house one by one (which would
# be very slow), you use smart strategies:

# HNSW (Hierarchical Navigable Small World)
# - Think of it like a layered city map:
# - Top layer = highways (coarse overview).
# - Middle layer = main roads.
# - Bottom layer = all streets and houses.
# - To find the nearest warehouse, you start at the highway level, zoom into the right district,
# then finally navigate down to the exact street.
# - This is what IndexHNSWFlat does: it builds a graph of connections so you can “hop” quickly
# to the right neighborhood.

#  IVF (Inverted File Index)
# - Imagine dividing the city into 256 neighborhoods (Voronoi cells).
# - First, figure out which neighborhood the customer’s house belongs to.
# - Then, only search inside that neighborhood instead of the whole city.
# - This is what IndexIVFFlat does: it clusters vectors and searches only in the most relevant
# clusters.
# - nprobe = 10 means you don’t just check one neighborhood, but the 10 most likely ones —
#  balancing speed and accuracy.

#  In Plain Words
# - HNSW = zooming in layer by layer on a city map.
# - IVF = splitting the city into neighborhoods and searching locally.
# - Both methods help you find the closest match fast without scanning all 100,000 houses.




!pip install faiss-cpu  # Install faiss

import faiss
import numpy as np

d = 384       # embedding dimension
n = 100_000   # number of vectors

# ── HNSW index ──────────────────────────────
index = faiss.IndexHNSWFlat(d, 32)  # M=32 neighbours
index.hnsw.efConstruction = 200     # build quality
index.hnsw.efSearch = 100           # query quality

vectors = np.random.randn(n, d).astype("float32")
faiss.normalize_L2(vectors)         # L2 normalize
index.add(vectors)                  # add all vectors

query = np.random.randn(1, d).astype("float32")
faiss.normalize_L2(query)
D, I = index.search(query, k=10)    # top-10
print("Indices:", I[0])             # [2341, 8712, ...]
print("Distances:", D[0])           # cosine scores

nlist = 256   # number of Voronoi cells
quantizer = faiss.IndexFlatL2(d)
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist)
index_ivf.train(vectors)
index_ivf.add(vectors)
index_ivf.nprobe = 10               # cells to search

# OPTION A: Chroma (local, no API key needed)
!pip install chromadb
!pip install sentence-transformers
import chromadb
from sentence_transformers import SentenceTransformer

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create Chroma client and collection
client = chromadb.Client()  # or chromadb.PersistentClient(path="./db")
collection = client.create_collection("docs")

# Sample documents
documents = [
    "Python is a high-level programming language",
    "Machine learning models need training data",
    "Dogs are loyal and friendly animals",
    "Cats are independent and curious pets",
]

# Encode documents into embeddings
embeddings = model.encode(documents).tolist()

# Add to Chroma collection
collection.add(
    documents=documents,
    embeddings=embeddings,
    ids=[f"doc{i}" for i in range(len(documents))],
    metadatas=[{"source": "demo", "idx": i} for i in range(len(documents))]
)

# Query with semantic search
query = "What animals make good companions?"
q_emb = model.encode([query]).tolist()
results = collection.query(query_embeddings=q_emb, n_results=3)

# Print results
for doc, dist in zip(results["documents"][0], results["distances"][0]):
    print(f"[{dist:.3f}] {doc}")
